backend:
  image:
    repository: cibotminhminhchan/yas-inventory
    tag: "6e943da6f6f5fd40151aae32fb2ed236ff78984e"

  nameOverride: inventory
  fullnameOverride: inventory
  databaseName: inventory
  ingress:
    enabled: false
