backend:
  image:
    repository: cibotminhminhchan/yas-inventory
    tag: "73898881709ecf26b46ba4fe273d5f800ba66984"

  nameOverride: inventory
  fullnameOverride: inventory
  databaseName: inventory
  ingress:
    enabled: false
