backend:
  image:
    repository: cibotminhminhchan/yas-inventory
    tag: "e8913ab83d3a9ab8c78fba3ef2e65a789cac07de"

  nameOverride: inventory
  fullnameOverride: inventory
  databaseName: inventory
  ingress:
    enabled: false
