apiVersion: v2
name: redis
description: Redis for YAS BFF session storage
type: application
version: 0.1.0
dependencies:
  - name: redis
    version: "20.x.x"
    repository: "https://charts.bitnami.com/bitnami"
