ui:
  image:
    repository: cibotminhminhchan/yas-storefront
    tag: "40e4dcdcbccb3c0677b2f3bfd04504b3a015081e"
  nameOverride: storefront-ui
  fullnameOverride: storefront-ui
#  extraVolumes:
#    - name: storefront-env-production
#      configMap:
#        name: storefront-env-production-configmap
#        items:
#          - key: .env.production
#            path: .env.production
#  extraVolumeMounts:
#    - name: storefront-env-production
#      mountPath: /app/.env.production
#      readOnly: true
#      subPath: .env.production
  extraEnvs:
    - name: API_BASE_PATH
      value: http://storefront.yas.local.com/api
  ingress:
    enabled: false   # <--- CHANGE THIS TO FALSE
    # hosts:
    #   - host: storefront.yas.local.com
    #     paths:
    #       - path: /
    #         pathType: ImplementationSpecific

#storefrontEnvProduction: |
#  API_BASE_PATH=http://storefront.yas.local.com:31273/api