backend:
  image:
    repository: cibotminhminhchan/yas-product
    tag: "e8913ab83d3a9ab8c78fba3ef2e65a789cac07de"

  nameOverride: product
  fullnameOverride: product
  databaseName: product
  ingress:
    enabled: false
  extraVolumes:
    - name: product-application-config
      configMap:
        name: product-application-configmap
  extraVolumeMounts:
    - name: product-application-config
      mountPath: /opt/yas/product
  extraApplicationConfigPaths:
    - /opt/yas/product/product-application.yaml  
