ui:
  image:
    repository: cibotminhminhchan/yas-backoffice-ui
    tag: "2f1e0e07da69a721f0dff465eeb20afe08fdae06"
  nameOverride: backoffice-ui
  fullnameOverride: backoffice-ui
  ingress:
    enabled: false
    # hosts:
    #   - host: backoffice.yas.local.com
    #     paths:
    #       - path: /
    #         pathType: ImplementationSpecific