ui:
  image:
    repository: cibotminhminhchan/yas-backoffice-ui
    tag: "ac4bc75e83bc8057ae26208771f9ecacc2616ea8"
  nameOverride: backoffice-ui
  fullnameOverride: backoffice-ui
  ingress:
    enabled: false
    # hosts:
    #   - host: backoffice.yas.local.com
    #     paths:
    #       - path: /
    #         pathType: ImplementationSpecific