ui:
  image:
    repository: ghcr.io/nashtech-garage/yas-backoffice
    tag: latest
  nameOverride: backoffice-ui
  fullnameOverride: backoffice-ui
  ingress:
    enabled: false
    # hosts:
    #   - host: backoffice.yas.local.com
    #     paths:
    #       - path: /
    #         pathType: ImplementationSpecific