apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: enable-strict-mtls-dev
  namespace: dev
spec:
  mtls:
    mode: STRICT
  portLevelMtls:
    80:
      mode: PERMISSIVE

---
# AuthorizationPolicy: allow `order` and `storefront-bff` services to call `cart` service
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-order-to-cart
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cart
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - "cluster.local/ns/dev/sa/order"
        - "cluster.local/ns/dev/sa/storefront-bff"

---
# AuthorizationPolicy: allow `order`, `storefront-bff`, and `backoffice-bff` services to call `inventory` service
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-order-to-inventory
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - "cluster.local/ns/dev/sa/order"
        - "cluster.local/ns/dev/sa/storefront-bff"
        - "cluster.local/ns/dev/sa/backoffice-bff"

---
# AuthorizationPolicy: allow only `order` service to call `tax` service
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-order-to-tax
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tax
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/dev/sa/order"]

---
# VirtualService for tax service: retry on 5xx
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tax-retry
  namespace: dev
spec:
  hosts:
  - tax
  http:
  - route:
    - destination:
        host: tax
        port:
          number: 80
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: "5xx"
