backend:
  image:
    repository: cibotminhminhchan/yas-order
    tag: "6e943da6f6f5fd40151aae32fb2ed236ff78984e"

  nameOverride: order
  fullnameOverride: order
  databaseName: order
  ingress:
    enabled: false
  extraVolumes:
    - name: order-application-config
      configMap:
        name: order-application-configmap
  extraVolumeMounts:
    - name: order-application-config
      mountPath: /opt/yas/order
  extraApplicationConfigPaths:
    - /opt/yas/order/order-application.yaml  