backend:
  image:
    repository: cibotminhminhchan/yas-order
    tag: "73898881709ecf26b46ba4fe273d5f800ba66984"

  nameOverride: order
  fullnameOverride: order
  databaseName: order
  ingress:
    enabled: false
  extraVolumes:
    - name: order-application-config
      configMap:
        name: order-application-configmap
  extraVolumeMounts:
    - name: order-application-config
      mountPath: /opt/yas/order
  extraApplicationConfigPaths:
    - /opt/yas/order/order-application.yaml  