apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-operator
    targetRevision: "*"
  destination:
    server: https://kubernetes.default.svc
    namespace: elasticsearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PhamMinhTrietHCMUS/yas-cd-project.git
    targetRevision: main
    path: k8s/deploy/elasticsearch/elasticsearch-cluster
    helm:
      parameters:
        - name: elasticsearch.replicas
          value: "1"
        - name: kibana.ingress.hostname
          value: "kibana.yas.local.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: elasticsearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
