apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
    istio-injection: enabled
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/PhamMinhTrietHCMUS/yas-cd-project.git
    targetRevision: main
    path: k8s/deploy/keycloak/keycloak
    helm:
      parameters:
        - name: hostname
          value: "identity.yas.local.com"
        - name: postgresql.username
          value: "yasadminuser"
        - name: postgresql.password
          value: "admin"
        - name: bootstrapAdmin.username
          value: "admin"
        - name: bootstrapAdmin.password
          value: "admin"
        - name: backofficeRedirectUrl
          value: "http://*"
        - name: storefrontRedirectUrl
          value: "http://*"
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
