apiVersion: v1
kind: Namespace
metadata:
  name: zookeeper
  labels:
    istio-injection: enabled
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zookeeper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PhamMinhTrietHCMUS/yas-cd-project.git
    targetRevision: main
    path: k8s/deploy/zookeeper
  destination:
    server: https://kubernetes.default.svc
    namespace: zookeeper
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
