apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-configuration-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" # This forces it to deploy FIRST
spec:
  project: default
  source:
    repoURL: https://github.com/PhamMinhTrietHCMUS/yas-cd-project.git
    targetRevision: HEAD
    path: k8s/charts/yas-configuration
    helm:
      parameters:
        # Pushing the dev prefix to the newly parameterized master-api-ingress
        - name: apiHostname
          value: dev-api.yas.local.com
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true