apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: yas-staging-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # 1. Backend Core Services
          - name: product
            imagePath: backend.image.repository
            imageRepo: cibotminhminhchan/yas-product
            ingressHost: internal-only.local
          - name: cart
            imagePath: backend.image.repository
            imageRepo: cibotminhminhchan/yas-cart
            ingressHost: internal-only.local
          - name: order
            imagePath: backend.image.repository
            imageRepo: cibotminhminhchan/yas-order
            ingressHost: internal-only.local
          - name: customer
            imagePath: backend.image.repository
            imageRepo: cibotminhminhchan/yas-customer
            ingressHost: internal-only.local
          - name: inventory
            imagePath: backend.image.repository
            imageRepo: cibotminhminhchan/yas-inventory
            ingressHost: internal-only.local
          - name: tax
            imagePath: backend.image.repository
            imageRepo: cibotminhminhchan/yas-tax
            ingressHost: internal-only.local
          - name: media
            imagePath: backend.image.repository
            imageRepo: cibotminhminhchan/yas-media
            ingressHost: internal-only.local
          - name: search
            imagePath: backend.image.repository
            imageRepo: cibotminhminhchan/yas-search
            ingressHost: internal-only.local
          # 2. BFFs
          - name: storefront-bff
            imagePath: backend.image.repository
            imageRepo: cibotminhminhchan/yas-storefront-bff
            ingressHost: staging-storefront.yas.local.com
          - name: backoffice-bff
            imagePath: backend.image.repository
            imageRepo: cibotminhminhchan/yas-backoffice-bff
            ingressHost: staging-backoffice.yas.local.com
          # 3. UIs (Notice the different imagePath, just like your Jenkins if/else!)
          - name: storefront-ui
            imagePath: ui.image.repository
            imageRepo: cibotminhminhchan/yas-storefront
            ingressHost: staging-storefront.yas.local.com
          - name: backoffice-ui
            imagePath: ui.image.repository
            imageRepo: cibotminhminhchan/yas-backoffice
            ingressHost: staging-backoffice.yas.local.com
          # 4. Documentation
          - name: swagger-ui
            imagePath: image.repository
            imageRepo: swaggerapi/swagger-ui
            # tagPath: image.tag
            # tagValue: v4.16.0 # Keeping the default swagger tag
            ingressHost: staging-api.yas.local.com
  template:
    metadata:
      name: '{{name}}-staging'
    spec:
      project: default
      source:
        repoURL: https://github.com/PhamMinhTrietHCMUS/yas-cd-project.git
        targetRevision: HEAD
        path: 'k8s/charts/{{name}}'
        helm:
          parameters:
            # This perfectly injects your Jenkins dynamic variables
            - name: '{{imagePath}}'
              value: '{{imageRepo}}'
            - name: ingress.hosts[0].host
              value: '{{ingressHost}}'
            - name: ingress.hosts[0].paths[0].path
              value: /
            - name: ingress.hosts[0].paths[0].pathType
              value: ImplementationSpecific
            - name: backend.image.pullPolicy
              value: Always
            - name: backend.serviceMonitor.enabled
              value: "false"
            - name: serviceMonitor.enabled
              value: "false"
      destination:
        server: https://kubernetes.default.svc
        namespace: staging
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true