apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swagger-ui-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/PhamMinhTrietHCMUS/yas-cd-project.git
    targetRevision: HEAD
    path: k8s/charts/swagger-ui
    helm:
      parameters:
        - name: ingress.host
          value: staging-swagger.yas.local.com
        - name: ingress.hosts[0].host
          value: staging-swagger.yas.local.com
        - name: ingress.hosts[0].paths[0].path
          value: /
        - name: ingress.hosts[0].paths[0].pathType
          value: ImplementationSpecific
        # --- THE STAGING SPECIFIC OVERRIDE ---
        - name: urls
          value: "[{ url: 'http://staging-api.yas.local.com/product/v3/api-docs', name: 'Product' }, { url: 'http://staging-api.yas.local.com/media/v3/api-docs', name: 'Media' }, { url: 'http://staging-api.yas.local.com/customer/v3/api-docs', name: 'Customer' }, { url: 'http://staging-api.yas.local.com/cart/v3/api-docs', name: 'Cart'}, { url: 'http://staging-api.yas.local.com/order/v3/api-docs', name: 'Order'}, { url: 'http://staging-api.yas.local.com/inventory/v3/api-docs', name: 'Inventory'}, { url: 'http://staging-api.yas.local.com/tax/v3/api-docs', name: 'Tax' }, { url: 'http://staging-api.yas.local.com/search/v3/api-docs', name: 'Search'}]"
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true