backend:
  image:
    repository: cibotminhminhchan/yas-media
    tag: "e8913ab83d3a9ab8c78fba3ef2e65a789cac07de"

  nameOverride: media
  fullnameOverride: media
  databaseName: media
  ingress:
    enabled: false
  extraVolumes:
    - name: media-application
      configMap:
        name: media-application-configmap
  extraVolumeMounts:
    - name: media-application
      mountPath: /opt/yas/media
  extraApplicationConfigPaths:
    - /opt/yas/media/media-application.yaml

