backend:
  image:
    repository: cibotminhminhchan/yas-cart
    tag: "4ddfc0f451ee8b7f6e94df416c27b9f528c79d7a"

  nameOverride: cart
  fullnameOverride: cart
  databaseName: cart
  ingress:
    enabled: false
  extraVolumes:
    - name: cart-application-config
      configMap:
        name: cart-application-configmap
  extraVolumeMounts:
    - name: cart-application-config
      mountPath: /opt/yas/cart
  extraApplicationConfigPaths:
    - /opt/yas/cart/cart-application.yaml
