backend:
  image:
    repository: cibotminhminhchan/yas-cart
    tag: "ac4bc75e83bc8057ae26208771f9ecacc2616ea8"

  nameOverride: cart
  fullnameOverride: cart
  databaseName: cart
  ingress:
    enabled: false
  extraVolumes:
    - name: cart-application-config
      configMap:
        name: cart-application-configmap
  extraVolumeMounts:
    - name: cart-application-config
      mountPath: /opt/yas/cart
  extraApplicationConfigPaths:
    - /opt/yas/cart/cart-application.yaml
