backend:
  image:
    repository: cibotminhminhchan/yas-cart
    tag: "e93c41f753f716f4629481caf303f0c82080e74b"

  nameOverride: cart
  fullnameOverride: cart
  databaseName: cart
  ingress:
    enabled: false
  extraVolumes:
    - name: cart-application-config
      configMap:
        name: cart-application-configmap
  extraVolumeMounts:
    - name: cart-application-config
      mountPath: /opt/yas/cart
  extraApplicationConfigPaths:
    - /opt/yas/cart/cart-application.yaml
