backend:
  image:
    repository: cibotminhminhchan/yas-sampledata
    tag: "617cfcb3b00ea00a6bb9fdd801a4098a9b49dbd5"

  nameOverride: sampledata
  fullnameOverride: sampledata
  databaseName: sampledata
  ingress:
    enabled: false
  extraVolumes:
    - name: sampledata-application
      configMap:
        name: sampledata-application-configmap
  extraVolumeMounts:
    - name: sampledata-application
      mountPath: /opt/yas/sampledata
  extraApplicationConfigPaths:
    - /opt/yas/sampledata/sampledata-application.yaml
