backend:
  image:
    repository: cibotminhminhchan/yas-tax
    tag: "3124adab27bc51d8e3fa4645c972d80e71611f56"

  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  ingress:
    enabled: false
