backend:
  image:
    repository: cibotminhminhchan/yas-tax
    tag: "0bb741e806ed2d5dd7f8e4850ae9c8cf1814369c"

  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  ingress:
    enabled: false
